import { Product } from '../../../typs/product';

export const Products: Product[] = [
  {
    id: 1,
    name: "Men's Cotton T-Shirt",
    description: 'Soft and comfortable cotton t-shirt for men.',
    price: 19.99,
    category: 'men',
    size: ['S', 'M', 'L', 'XL'],
    color: ['black', 'white', 'blue'],
    image: 'https://dummyimage.com/295x298',
    stock: 50,
    rate: 4,
  },
  {
    id: 2,
    name: "Women's Denim Jacket",
    description: 'Trendy and durable denim jacket for women.',
    price: 49.99,
    category: 'women',
    size: ['S', 'M', 'L'],
    color: ['blue', 'black'],
    image: 'https://dummyimage.com/295x298',
    stock: 30,
    rate: 4,
  },
  {
    id: 3,
    name: 'Unisex Hoodie',
    description: 'Warm unisex hoodie with front pocket.',
    price: 39.99,
    category: 'unisex',
    size: ['S', 'M', 'L', 'XL', 'XXL'],
    color: ['grey', 'black', 'green'],
    image: 'https://dummyimage.com/295x298',
    stock: 60,
    rate: 4,
  },
  {
    id: 4,
    name: 'Unisex Hoodie',
    description: 'Warm unisex hoodie with front pocket.',
    price: 39.99,
    category: 'unisex',
    size: ['S', 'M', 'L', 'XL', 'XXL'],
    color: ['grey', 'black', 'green'],
    image: 'https://dummyimage.com/295x298',
    stock: 60,
    rate: 4,
  },
  {
    id: 5,
    name: "Men's Slim Fit Jeans",
    description: 'Stylish slim fit jeans for men made from high-quality denim.',
    price: 34.99,
    category: 'men',
    size: ['30', '32', '34', '36'],
    color: ['blue', 'black'],
    image: 'https://dummyimage.com/295x298',
    stock: 40,
    rate: 5,
  },
  {
    id: 6,
    name: "Women's Summer Dress",
    description: 'Lightweight and breezy dress perfect for summer.',
    price: 29.99,
    category: 'women',
    size: ['S', 'M', 'L'],
    color: ['red', 'yellow', 'white'],
    image: 'https://dummyimage.com/295x298',
    stock: 35,
    rate: 4,
  },
  {
    id: 7,
    name: "Kid's Graphic T-Shirt",
    description: 'Fun graphic tee for kids made of 100% cotton.',
    price: 14.99,
    category: 'kids',
    size: ['XS', 'S', 'M'],
    color: ['green', 'blue', 'white'],
    image: 'https://dummyimage.com/295x298',
    stock: 45,
    rate: 4,
  },
  {
    id: 8,
    name: 'Men’s Formal Shirt',
    description: 'Elegant formal shirt suitable for office or occasions.',
    price: 27.99,
    category: 'men',
    size: ['M', 'L', 'XL'],
    color: ['white', 'light blue'],
    image: 'https://dummyimage.com/295x298',
    stock: 20,
    rate: 5,
  },
  {
    id: 9,
    name: "Women's Yoga Pants",
    description: 'Comfortable and stretchable yoga pants for women.',
    price: 24.99,
    category: 'women',
    size: ['S', 'M', 'L', 'XL'],
    color: ['black', 'grey', 'purple'],
    image: 'https://dummyimage.com/295x298',
    stock: 25,
    rate: 4,
  },
  
];
